### ISSUE TITLE
[suggestion] fix UX with plextraktsync

### ISSUE THREAD

**Issue by funkypenguin** [elfhosted/enhancements#20]
### 🤪 Sanity check

- [X] I have searched and confirmed no existing [open](https://github.com/elfhosted/enhancements/issues?q=is%3Aissue) / [closed](https://github.com/elfhosted/enhancements/issues?q=is%3Aissue+is%3Aclosed) issues, or [open](https://github.com/elfhosted/enhancements/pulls?q=is%3Apr) / [closed](https://github.com/elfhosted/enhancements/pulls?q=is%3Apr+is%3Aclosed) PRs exist for this app

### 🤕 What's not right?

Plextraktsync automatically creates a bunch of non-working Plex URLs in its `config.yml`. These could all be replaced with just `http://plex:32400`.

Further, the default timeout is too short, and can be extended in the same file.

### 🤯 Here's my idea!

Make these changes automatically

### 🤔 On the other hand..

-

### 🤩 But will it fly?

-

**Comment by funkypenguin** [comment]
Here's an example .yml - if we can work out a `yq` command to replace the values of the Plex URLs, we can do it automatically:

```yaml
servers:
  default:
    token: null
    urls:
    - null
    - null
    id: null
    config: null
  Plex:
    token: <redacted>
    urls:
    - http://plex:32400
    id: <redacted>
    config: null
```
